### ISSUE TITLE
Current selected branch not updating on Plugins page list?

### ISSUE THREAD

**Issue by rob** [afragen/github-updater#592] opened 2017-08-22 16:02 UTC
I updated the Pods plugin to the `release/2.7` branch, and it did update fine, but the Plugins list page always says the current branch is `master`.

This happens even on the `develop` branch of GitHub Updater.

I tried the "Refresh Cache" button in GitHub Updater's settings as well, but nothing happens.

![screen shot 2017-08-22 at 10 30 40 am](https://user-images.githubusercontent.com/503/29570630-02b32c88-8725-11e7-861c-270eb77538d5.png)

![screen shot 2017-08-22 at 10 30 05 am](https://user-images.githubusercontent.com/503/29570597-eb6a2cca-8724-11e7-8b70-ce926b75e500.png)

**Comment by afragen** [comment] 2017-08-22 16:30
You will need to use the branch switcher to reinstall the branch to correctly set the branch name. This was a new change for v7.0.0. 

After doing this, the correct branch name will show in the branch switch row of the plugins page.

**Comment by rob** [comment] 2017-08-22 16:38
Do you mean click 'another version' and select the same branch (e.g., release/2.7)?

Or do I have to re-install the plugin from `Settings > GitHub Updater > Install Plugin`?

**Comment by afragen** [comment] 2017-08-22 17:34
First choice. Reinstall Pods branch `release/2.7`

**Comment by afragen** [comment] 2017-08-23 17:58
I cannot replicate what is in your video. Can you give details about your environment?

**Comment by idpaterson** [comment] 2017-08-23 20:51
I am having the same issue with switching to the develop branch for my Bitbucket repositories. There is no `current_branch_*` value in my `github_updater` options value.

**Comment by afragen** [comment] 2017-08-23 21:00
Can this be replicated in a standard WP installation with default theme and only GitHub Updater and your plugin active?

**Comment by rob** [comment] 2017-08-24 00:20
I tested this locally with Local by Flywheel and it works fine switching between branches with just GitHub Updater and Pods installed. I'll have to clone the production site tomorrow and test it out by disabling all plugins. Maybe there's a conflict somewhere.

(Thought maybe it's because we have InfiniteWP installed, but I deactivated that and it's still happening.)

**Comment by afragen** [comment] 2017-08-24 00:33
Thanks @rob 

Please let me know what plugin is causing the conflict and hopefully I’ll be able to figure out what’s causing it.

**Comment by idpaterson** [comment] 2017-08-24 14:07
@rob maybe start with any overlap with [my plugins](https://0bin.net/paste/zJPMSklLmgyLAQmC#82PpzcOxgGDpQoNQbVXOCPIklr6SEkEV0nGcYw+bZqz)? I'll try Local as well.

**Comment by idpaterson** [comment] 2017-08-24 15:01
This may not be related to plugins; a fresh install works fine but has a slightly different format for the `github_updater` option value. After upgrading from earlier versions without reconfiguring the plugin my database entry looks like this:

```
Array
(
    [bitbucket_password] => xx
    [bitbucket_server_password] => 
    [bitbucket_server_username] => 
    [bitbucket_username] => xx
    [branch_switch] => 1
    [db_version] => 7000
    [github_access_token] => 
    [xx-wordpress-plugin] => 1
)
```

However, on the clean local install I get two new keys, `github-updater` and `current_branch_*`:

```
Array
(
    [bitbucket_password] => xx
    [bitbucket_server_password] => 
    [bitbucket_server_username] => 
    [bitbucket_username] => xx
    [branch_switch] => 1
    [current_branch_xx-wordpress-plugin] => master
    [db_version] => 7000
    [github_access_token] => 
    [github-updater] => 
    [xx-wordpress-plugin] => 1
)
```

Does this seem to be a possible cause of the problem or just a symptom of it? Is this a case of needing to remove and re-add the repositories when upgrading from old versions, or was the old data supposed to be updated automatically?

**Comment by idpaterson** [comment] 2017-08-24 15:57
Deleting and reinstalling my Bitbucket plugins did not work, nor did deleting and reinstalling GitHub Updater, nor did mirroring the `github_updater` preference from the working install. Rob, is there any overlap in our installed plugins?

**Comment by rob** [comment] 2017-08-24 18:17
@idpaterson, here's my list:

https://gist.github.com/rob/f4135064abf8d8fe29a2a692b601bd94

The only two I see overlapping are Akismet and User Switching. I disabled both, and still have the issue, so I don't think it's those.

I'll try to disable all of the plugins later today and see if it still happens.

**Comment by afragen** [comment] 2017-08-24 18:26
I use both of those plugins on my test sites.

**Comment by idpaterson** [comment] 2017-08-24 19:44
A little bit of debug output made the problem very obvious. In my case, the `set_branch_on_switch` filter is getting called first by a different plugin that is doing a license check. The hook is triggered with that url rather than the one corresponding to the HTTP request from github-updater. 

So I am seeing `set_branch_on_switch` called with `$url = 'https://divilife.com/?wc-api=upgrade-api&request=pluginupdatecheck&slug=divi-overlays&...'`. The url does not match any repository so the `current_branch_*` value is not updated. Furthermore, the `set_branch_on_switch` filter is removed after the first HTTP response so the response from the update check is never handled.

**Comment by idpaterson** [comment] 2017-08-24 19:54
The updater for this plugin uses the `pre_set_site_transient_update_plugins` action to perform the HTTP request that is coming in before the one that `github-updater` expects.

**Comment by afragen** [comment] 2017-08-24 19:57
What plugin are you referring to? Is there a remove_filter call in it?

**Comment by idpaterson** [comment] 2017-08-24 20:13
It does not seem to have a remove_filter call, this is the Divi Overlays plugin... I disabled it to see if anything else pops up: http://www.elegantthemes.com/api/api.php which is probably the Divi license check behaving in the same way.

So, I commented out the remove_filter from `set_branch_on_switch` to see how many of these were coming through before the intended response. The above elegantthemes.com request was followed by https://api.wordpress.org/plugins/update-check/1.1/ then another elegantthemes.com then finally the bitbucket repository that I was updating. After all that, the branch was properly switched.

If there is no better way to handle the status change than this hook, it appears that it may need to be removed only when the URL matches a response you intended to handle.

**Comment by afragen** [comment] 2017-08-24 23:02
The hook is just a mechanism to capture the URL and the branch switch. Nothing happens to the data from the hook. My remove_filter only should only remove my `set_on_branch_switch`. Which is only called from my add_action in Branch constructor.

Adding and removing filters is sorta a best practice and won’t find the root cause of this issue.

**Comment by afragen** [comment] 2017-08-24 23:07
> Does this seem to be a possible cause of the problem or just a symptom of it? Is this a case of needing to remove and re-add the repositories when upgrading from old versions, or was the old data supposed to be updated automatically?

This is expected behavior. My changelog for 7.0.0 clearly describes this breaking change, which is why reinstalling the branch of your plugin is needed to properly set that value.

**Comment by afragen** [comment] 2017-08-24 23:10
There really isn’t any shortcut to finding a plugin conflict than by activating and deactivating groups of plugins.

**Comment by idpaterson** [comment] 2017-08-25 01:28
I think there may have been a misunderstanding, here is what I am seeing:

1. Branch constructor sets up the filter to call `set_on_branch_switch`
2. `http_response` filter is triggered by a third-party plugin
3. `set_on_branch_switch` runs but cannot operate on the unexpected URL to update the database
4. `set_on_branch_switch` uses `remove_action` to prevent being called again
5. The filter is triggered by github-updater but `set_on_branch_switch` is no longer handling the filter
6. The bitbucket plugin has switched to the new branch, but the change does not persist since `set_on_branch_switch` did not record the branch

When I disabled the `remove_action` call inside `set_on_branch_switch` I was able to see all of the third-party plugins that were triggering the `http_response` filter *before* the response that github-updater intended the filter for. Eventually the filter was triggered with the correct URL and the branch was persisted to the database.

**Comment by afragen** [comment] 2017-08-25 01:33
Thanks, I think I understand now.

Rather than run passively wait for the hook, I may need specifically instantiate the Branch class. I’ll think about it but for now just comment out the remove_filter.

**Comment by rob** [comment] 2017-08-25 15:16
Hi guys,

I can confirm that commenting out the `remove_filter` for `http_response` fixes everything for me!

With that said, I'm not using the Divi plugin @idpaterson is using, but I am using Beaver Builder (another page builder plugin) as well as other paid plugins that do license checks, so I'm sure the same thing is happening here, just with another plugin.

![screen shot 2017-08-25 at 11 15 23 am](https://user-images.githubusercontent.com/503/29720081-b780669a-8986-11e7-97f6-5df34b29e192.png)

Thanks for tracking this down, @idpaterson.

**Comment by afragen** [comment] 2017-08-25 15:18
I have an idea on how to fix this without using a filter hook. I should have something by the end of the weekend to test as I'm traveling right now.

**Comment by afragen** [comment] 2017-08-26 17:04
This should be fixed in latest update. I've moved the trigger from a filter hook to a direct call.

Let me know if it works for you both.

**Comment by idpaterson** [comment] 2017-08-26 20:34
This looks like a great solution and works perfectly for me!

**Comment by afragen** [comment] 2017-08-26 20:50
Excellent!

**Comment by afragen** [comment] 2017-08-27 16:22
v7.1.0.8 should have the final changes. I messed up a conditional along the way. 🤦‍♂️

**Comment by rob** [comment] 2017-08-29 16:36
Late to the party, but it works! Thanks again for your hard work. :-) Thanks @idpaterson for figuring it out!

**Closed** 2017-08-30 01:25 UTC
Labels: bug, fixed
