### ISSUE TITLE
PCLZIP_ERR_BAD_FORMAT

### ISSUE THREAD

**Issue by wester97** [afragen/github-updater#693] opened 2018-06-11 15:55 UTC
BitBucket plugin/theme installs are throwing this error on `develop` but not on `master`.  Thanks!

**Comment by afragen** [comment] 2018-06-11 18:07
Are your Bitbucket credentials correct? You might try re-entering as this is usually an Auth error.

**Comment by wester97** [comment] 2018-06-12 19:08
Yes.  I used the same credentials with both `develop` and `master`.  The master branch worked right away.

**Comment by afragen** [comment] 2018-06-12 19:22
If you give `afragen` `read` access I can take a closer look and test on my end.

**Comment by wester97** [comment] 2018-06-12 20:29
Andy, I've added you.  :)

Thank you!

**Comment by afragen** [comment] 2018-06-13 00:04
@wester97 there doesn't seem to be a develop branch on Bitbucket. Have you pushed it from local?

You will also need to synchronize your `master` version and your tags.

**Comment by wester97** [comment] 2018-06-14 13:31
That's true, it only has `master` for now.

**Comment by afragen** [comment] 2018-06-14 14:48
Trying to update against a branch that currently doesn’t exist is the reason for the error. Let me know if you have any other issues.

**Comment by wester97** [comment] 2018-06-14 14:50
But, I should leave the branch empty for `master` right?  So, it should find my branch.  I left it empty in both your `master` and `develop` branch, with develop working right away.

**Comment by afragen** [comment] 2018-06-14 14:57
During an install if you leave the branch field empty it defaults to `master`. If you try to install a branch that doesn’t exist you will have an error of some sort.

Am I understanding your problem correctly?

**Comment by wester97** [comment] 2018-06-14 14:58
Right - I left it blank, which should default to master.  But, I received this error in your `develop` but not `master` branch.

**Comment by afragen** [comment] 2018-06-14 15:01
What version of `develop` are you using?

**Comment by wester97** [comment] 2018-06-14 15:03
7.6.2.24

**Comment by afragen** [comment] 2018-06-14 15:07
I was able to install your theme on my test server running the GHU develop branch v7.6.2.25, but I don’t think there are significant differences in the versions.

**Comment by afragen** [comment] 2018-06-14 15:19
Do you have any other Bitbucket hosted plugins you are using with GHU?

Can you provide a screenshot of the filled out install panel that fails and the failure?

**Comment by wester97** [comment] 2018-06-14 15:24
![github_updater_settings](https://user-images.githubusercontent.com/2837703/41421742-0c5fcdfa-6fbd-11e8-8561-43574d5511c5.png)
![github_updater_settings_error](https://user-images.githubusercontent.com/2837703/41421741-0c4ebdee-6fbd-11e8-9842-9c36b33b5c1a.png)

**Comment by afragen** [comment] 2018-06-14 15:39
Can you show a screenshot of the Bitbucket tab?

This is an Authentication error. Try re-entering your password.

I was able to install the theme.

**Comment by wester97** [comment] 2018-06-14 15:41
![github_updater_settings_bitbucket](https://user-images.githubusercontent.com/2837703/41422873-80c772f4-6fbf-11e8-94ab-3f10d189905f.png)

**Comment by afragen** [comment] 2018-06-14 15:43
Hmm, it should’ve saved those credentials. If you re-enter your credentials and check the box for a private repo, does it save the changes?

**Comment by afragen** [comment] 2018-06-14 15:44
I’ll do a little testing with a new install and see if I can replicate.

**Comment by wester97** [comment] 2018-06-14 15:52
I was able to save my credentials from the general settings tab, and then the install from Install Theme worked.

**Comment by afragen** [comment] 2018-06-14 17:03
I can reproduce this. Sorry I introduced a bug if this is the first time installing a Bitbucket private repo. Working on a fix now.

**Comment by wester97** [comment] 2018-06-14 17:09
No worries!  I LOVE the plugin and I'm eager to help with its advance.

**Comment by afragen** [comment] 2018-06-14 18:40
This should fix the issue https://github.com/afragen/github-updater/commit/3366b1e0d11596fcb2a674ddc324deeec87bc320

Close the issue if it does. Thanks for the bug report.

**Closed** 2018-06-20 15:41 UTC
Labels: bug, fixed
