### ISSUE TITLE
I get a white screen when i activate this plugin

### ISSUE THREAD

**Issue by roger2014jr** [afragen/github-updater#650] opened 2018-02-18 22:48 UTC
I'm using the latest WordPress with a multi-site install, Now I'm stuck and have to figure out how to uninstall this plugin manually

**Comment by afragen** [comment] 2018-02-19 05:58
Try adding `define( ‘WP_DEBUG’, true );` in you wp-config.php file to see where the error is.

**Comment by picasso** [comment] 2018-02-19 10:54
`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /wp-content/plugins/github-updater/src/Singleton.php on line 39, referer: /wp-admin/update-core.php`

**Comment by afragen** [comment] 2018-02-19 16:24
500 internal server errors are often difficult to figure out. https://www.google.com/search?q=500+internal+server+error

My test site have 768M allocated to memory. Most of these errors are related to htaccess files.

**Comment by afragen** [comment] 2018-02-19 16:25
Line 39 of Singleton is a call to the PHP function `debug_backtrace()`.

**Comment by afragen** [comment] 2018-02-19 16:37
For now you can comment out https://github.com/afragen/github-updater/blob/develop/src/Singleton.php#L39 until I can fix and test. This will likely cause several non-fatal PHP errors.

**Comment by reddog** [comment] 2018-02-19 17:32
Can confirm I also get the same error with a fresh install of WordPress 4.9.4 on Ubuntu 16.04.

Removing the `github-updater-develop` folder from `plugins` (I downloaded the zip from https://github.com/afragen/github-updater which appears to auto-download the `develop` branch), and using the `7.5.0` release from https://github.com/afragen/github-updater/releases/tag/7.5.0 , it looks like all is okay.

**Comment by afragen** [comment] 2018-02-19 19:09
Thanks @reddog. I believe the `debug_backtrace()` was a conditional call in the master branch but I changed to make it happen all the time. I’m working on a fix.

**Comment by afragen** [comment] 2018-02-20 01:55
Update to latest `develop` branch and let me know if the memory issue persists. Thanks.

**Comment by teolaz** [comment] 2018-02-22 14:39
Same error with last develop version, switched to 7.5.0 as suggested by @reddog and now it's working again...

**Comment by afragen** [comment] 2018-02-22 21:13
So the problem is that there is really no difference in Singleton.php from the develop branch to 7.5.0

I realize that this is where the error is firing but can people share anything else that they did to there installations in the same timeframe?

Does this issue persist in a local installation?

**Comment by afragen** [comment] 2018-02-22 21:14
Can people provide server details. PHP version, WP version, PHP memory available?

**Comment by afragen** [comment] 2018-03-02 05:00
Is there anything new? I’ve been unable to replicate this issue, does it still exist?

**Comment by tomkenkel** [comment] 2018-03-02 22:07
Still exists. WP 4.9.4; PHP 7.0.27, PHP Mem 256MB.

**Comment by afragen** [comment] 2018-03-03 06:37
Can we all test in a local environment. I’d like to try and replicate this but haven’t been able to.

Test using default theme and only with the GitHub Updater plugin active.

**Comment by tomkenkel** [comment] 2018-03-04 00:33
Using scotchbox. New WP install; twentyseventeen theme; GitHub Updater the only active plugin.

<img width="1156" alt="screenshot 2018-03-03 19 32 36" src="https://user-images.githubusercontent.com/270877/36940809-b0c0c5ec-1f19-11e8-9a13-547b64df412c.png">

**Comment by afragen** [comment] 2018-03-04 00:45
Can you rename `github-updater-develop` to `github-updater`?

**Comment by afragen** [comment] 2018-03-04 00:46
Are there any mu-plugins?

**Comment by afragen** [comment] 2018-03-04 00:50
@tomkenkel does switching to v7.5.0 work for you?

**Comment by tomkenkel** [comment] 2018-03-04 01:12
I renamed the directory. No fix.
No mu-plugins. Full plugin list is Akismet, Hello Dolly, and GitHub Updater. Only GHU is active.
7.5.0 works as expected. All previous versions of this plugin have been great. Thank you for making it!

**Comment by afragen** [comment] 2018-03-04 06:00
@tomkenkel I have to say I don’t really understand why 7.5.0 works but develop doesn’t. The Singleton class isn’t significantly different between the 2 versions.

**Comment by tomkenkel** [comment] 2018-03-04 21:31
I’m not good at PHP, but I don't think it's the class. Replacing the Singleton class in develop with the class from 7.5.0 creates a different error:
“Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes)…”

**Comment by afragen** [comment] 2018-03-04 22:17
The odd thing is there’s not a significant amount of difference in the develop branch.

Can you add the following in wp-config.php and check the debug.log in wp-content?

define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );

**Comment by tomkenkel** [comment] 2018-03-04 22:49
`[04-Mar-2018 22:36:29 UTC] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/public/site/wp-content/plugins/github-updater-develop/src/Singleton.php on line 42
`

**Comment by afragen** [comment] 2018-03-04 22:53
Interesting, a new error. Can you change the timeout? https://www.fdgweb.com/increase-php-timeout-values-apache-ngnix/

**Comment by afragen** [comment] 2018-03-04 23:38
Set the timeout for 600, humor me.

**Comment by afragen** [comment] 2018-03-04 23:55
Another thing to try is changing the line to the following.

`$backtrace = debug_backtrace( $limit = 2 );`

**Comment by afragen** [comment] 2018-03-04 23:55
Odd that a standard PHP function would timeout.

**Comment by afragen** [comment] 2018-03-06 09:00
Can you try the branch `no-backtrace` and let me know if that works?

**Comment by tomkenkel** [comment] 2018-03-06 13:22
Different error

`[06-Mar-2018 13:18:46 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 262144 bytes) in /var/www/public/site/wp-includes/option.php on line 1186
[06-Mar-2018 13:18:47 UTC] PHP Fatal error:  Allowed memory size of 805306368 bytes exhausted (tried to allocate 262144 bytes) in /var/www/public/site/wp-includes/load.php on line 679
`

This was run on Scotchbox’s recently updated server stack. I can try tonight with the stack I used when we started.

**Comment by afragen** [comment] 2018-03-06 14:26
Is there more in the error logs? This error doesn't seem to trace back to GitHub Updater directly, does it?

**Comment by afragen** [comment] 2018-03-08 05:15
I think I may have found an fixed this error. I think it may be related to #656 

Please test and let me know.

**Comment by tomkenkel** [comment] 2018-03-08 13:15
Installs and activates as expected. I was able to install and activate a theme from GitHub. I haven’t tried updating the theme. I started getting the cron warning below after updating [Scotchbox](https://box.scotch.io/).

Thanks for your persistence!

<img width="854" alt="screenshot 2018-03-08 08 08 38" src="https://user-images.githubusercontent.com/270877/37152751-615a434c-22a8-11e8-8c45-ef8c128f5948.png">

**Comment by afragen** [comment] 2018-03-08 14:22
That’s just a warning that WP-Cron hasn’t run in over 24 hours. If this persists it may mean that something in the server setup is interfering with how WP-Cron runs and you might need to create an actual cron job. Look at the wiki regarding background processing.

**Comment by afragen** [comment] 2018-03-09 21:46
@roger2014jr @teolaz @reddog @picasso please let me know if this issue is fixed for you. Thanks.

**Comment by afragen** [comment] 2018-03-10 15:51
@tomkenkel you can also turn off background processing with a filter to see if the issue is WP-Cron only.

`add_filter( 'github_updater_disable_wpcron', '__return_true' );`

**Comment by teolaz** [comment] 2018-03-12 13:25
@afragen updated to 7.5.0, cannot get again the same error on different sites :S

**Comment by afragen** [comment] 2018-03-12 13:27
The error was on the develop branch, not the release.

**Comment by afragen** [comment] 2018-03-24 17:26
This is fixed in latest `develop` branch. I had inadvertently created an infinite loop. 🤦‍♂️

**Closed by afragen** 2018-03-24 17:26 UTC
