### ISSUE TITLE
persist-admin-notices-dismissal issue

### ISSUE THREAD

**Issue by DSuds** [afragen/github-updater#453] opened 2016-09-21 18:53 UTC
I was seeing a lot of issues with the new action.  I thought github-updater/github-updater.php:76 should change from:
add_action( 'admin_init', array( '\PAnD', 'init' ) );
To
add_action( 'admin_init', array( 'PAnD', 'init' ) );

But I still see 
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'PAnD' not found in /usr/share/wordpress/wp-includes/plugin.php

**Comment by scarstens** [comment] 2016-09-21 19:26
yes we saw these too, I can confirm this one

**Comment by afragen** [comment] 2016-09-21 23:47
@DSuds since I've namespaced GitHub Updater, any other class called in a namespaced class needs to be escaped. Technically, this is called in github-updater.php which is not namespaced. So I'm not sure it matters.

Is the error persistent?

@scarstens do you still see this?

**Comment by scarstens** [comment] 2016-09-22 02:41
Yes I was just seeing this on the site error logs where we are also doing the github updater notifications not working testing. I think we actually had to disable the GHU plugin on one of our sites because after update it blew up our notifications at New Relic when the error rate spiked.

**Comment by afragen** [comment] 2016-09-22 04:04
I have an idea, I'll post back here when to update develop and test.

**Comment by afragen** [comment] 2016-09-22 17:55
I just pushed a commit, https://github.com/afragen/github-updater/commit/00c1cc533fb99ea1f65c0571752a71c4cba86649 , the hopefully fixes this issue.

Please let me know. Update to develop v5.6.1.3

**Comment by afragen** [comment] 2016-09-22 18:14
😫 I'm still seeing this error in the logs, but interestingly it doesn't fatal the actual site and even with WP_DEBUG = true, no error is displayed.

I've traced the flow through and the class is loading. If there's any way to suppress the error? Looking in that direction now.

**Comment by afragen** [comment] 2016-09-22 19:28
Just committed something to stop this from being called when DOING_AJAX. I haven't seen another error in the logs since. 

develop 5.6.1.4, can anyone confirm?

**Comment by afragen** [comment] 2016-09-22 21:44
I received confirmation from Seth that the fix from DOING_AJAX seems to be working. I'm going to close this issue. Please reopen if it shows up again.

**Comment by afragen** [comment] 2016-09-23 19:24
I found the problem, I think. Fix committed in develop.

In `persist-admin-notices-dismissal.php` the early exit during heartbeat was before the class declaration. I just removed it.

**Closed** 2016-09-23 19:27 UTC
