### ISSUE TITLE
Site Backend is really slow

### ISSUE THREAD

**Issue by JoeHana** [afragen/github-updater#183] opened 2015-03-11 12:35 UTC
We're using Github Updater for around 20 Plugins from Bitbucket (Private Repos) and Github. The majority of those is hosted on Bitbucket. And it feels like the site has been slowing down since then.

By investigating the code from the Github Updater it seems like the APIS of Github and Bitbucket are included and queried every time a request hits wordpress. (Plugin.php), which can indeed slow down the whole site.

Wouldn't it be better to perform this occasionally on a given interval? Or even better check only 3-5 plugins at a time and after some pause check the next 3-5 plugins?

**Comment by afragen** [comment] 2015-03-11 13:35
The APIs are checked and the results cached for 12 hours. The only results that aren't cached are 403 and 401 results and they will now throw an error message. On the backend the plugin also seems to run with every heartbeat and page load so you can see after the initial time hit its really pretty quick. In my testing, after caching, it takes somewhere between 0.02 to 0.15 sec to run.

Believe me I understand about having many plugins and themes to check and the slowness of the hit. This will only occur for admin level users and usually only the first check of the day. If you can think of a good way to chunk the number of plugin's being checked in a multi-threaded fashion I'm open to any speed improvements.

**Comment by szepeviktor** [comment] 2015-03-11 17:38
Query Monitor will show you what is going on: https://github.com/johnbillion/query-monitor

**Comment by szepeviktor** [comment] 2015-03-11 17:40
I have tha smaeish problem.
Developed this time-saver:
https://github.com/szepeviktor/wordpress-plugin-construction/blob/master/mu-disable-updates/disable-updates.php
You can do updates with a real (CLI) cron job or use *non-mouse* wp-cli for management.

**Comment by szepeviktor** [comment] 2015-03-11 17:42
@afragen Could you take a look at my short plugin and tell me is it blocking GHU also?

**Comment by afragen** [comment] 2015-03-12 05:14
@szepeviktor  I'll check but it will be a couple of days till I can get to it.

**Comment by szepeviktor** [comment] 2015-03-12 05:40
OK!

**Comment by afragen** [comment] 2015-03-16 23:20
I think it's blocking GHU update checks too.

**Comment by szepeviktor** [comment] 2015-03-16 23:21
@afragen Thank you.

**Comment by deancsmith** [comment] 2015-05-16 08:18
+1 seems to be causing CURL errors on the admin, because the access permissions are not set up properly on the Github/Bitbucket repos. Could the plugin be updated to cache even 404/403 errors for a time? (with the option to clear these/change the cache time, for debugging purposes?)

**Comment by afragen** [comment] 2015-05-16 14:55
@deancsmith there's really no simple way to chunk API checks without really causing the update checks to be really delayed. Consider that each plugin has 4-5 API calls, all of which are cached except for auth errors. 404s are cached.

As these calls only effect an admin/superadmin user and then only every 12 hours or so, I'm not sure I see the benefit. The long page loads are only when transients need to be updated and that's only on demand or every 12 hours.

When using Query Monitor and the checks are not hitting the API the page load times are less than a sec.

**Comment by deancsmith** [comment] 2015-05-17 03:26
@afragen 

Apologies but Wordpress is really not my forte and I did not set up the instances that I am currently looking at. In Query Monitor, I am getting the following two errors on every page load of the WP Admin (with a 1 sec delay with each).

![image](https://cloud.githubusercontent.com/assets/387289/7668884/904a43c6-fc97-11e4-91e7-f93826d4dc1f.png)

They are on Bitbucket instead of Github, if that is relevant, and they actually appear to be 404s to CURL but when I open the actual plugin link in Chrome, I get redirected to a 403.

![image](https://cloud.githubusercontent.com/assets/387289/7668892/00e95914-fc98-11e4-8578-50ef30c67939.png)

These do not appear to be being cached, although potentially the plugin is also incorrectly configured? (although I can't see any settings that could be the cause) I'm running version 4.4.0 of the plugin.

**Comment by afragen** [comment] 2015-05-17 14:41
Can you add `afragen` with `read` privileges if this is a private repo so that I may test and see? 404s should be cached and a 403 should be an authentication issue that would give an admin notice.

**Comment by deancsmith** [comment] 2015-05-19 07:48
They aren't my repos either. @bengummer can we share one?

**Comment by deancsmith** [comment] 2015-05-25 09:59
@afragen Actually, I think you can close this issue. The problem may be related to the way some of our plugins are configured, and so we'll raise a separate issue if we can replicated a specific bug in the plugin.

Thanks for offering to help!

**Closed** 2015-05-25 14:13 UTC

**Comment by cbratschi** [comment] 2016-01-21 13:47
I have the same issue. A Bitbucket repository is used but the plugin still queries GitHub, gets and error and connects again and again. WordPress is very slow due to this. If the plugin is deactivated everything is fine again.

Please do not send requests to GitHub if Bitbucket is configured.

**Comment by afragen** [comment] 2016-01-21 13:52
GitHub will only be checked if there is a plugin/theme with the GitHub header. 404s are cached so it's inly checked every 12 hours.

**Comment by cbratschi** [comment] 2016-01-21 14:00
After disabling and activating the plugin the performance is better and there are no longer slow HTTP connections shown. I keep on monitoring this issue.

**Comment by afragen** [comment] 2016-01-22 13:57
FYI, GitHub will always be polled as this plugin itself is on GitHub.
