### ISSUE TITLE
Gitlab with sub-group does not work

### ISSUE THREAD

**Issue by sadortun** [afragen/github-updater#556] opened 2017-05-26 04:35 UTC
Hi @afragen,

With Gitlab new Sub-group feature, the plugin does not handle correctly the path.

If you enter the following plugin URL
`https://gitlab.com/issue-packagist-784/my_sub_group/test_project.git`

The plugin converts it to :
`https://gitlab.com/issue-packagist--84/my_sub_group/repository/archive.zip?ref=master…`

Log
```
Downloading install package from https://gitlab.com/issue-packagist--84/my_sub_group/repository/archive.zip?ref=master…

Unpacking the package…

The package could not be installed. PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature
```

**Comment by afragen** [comment] 2017-05-26 04:40
I'm not sure what a subgroup is nor why it is preferable to a standard repository. Can you provide details?

**Comment by sadortun** [comment] 2017-05-26 04:43
Well, a  group is only a way to organize repositories. Instead of having hundreds of them in the single `namespace`

https://about.gitlab.com/2017/03/22/gitlab-9-0-released/#subgroups-ce-ee

**Comment by afragen** [comment] 2017-05-26 04:46
It doesn't surprise me that it doesn't work. GHU wasn't designed to use subdirectories.

**Comment by sadortun** [comment] 2017-05-26 04:48
Any possibility of making it work ? Is it a small tweak of a large refactor ?

The only actual change is that the  repository URL will contain sub-directories.

**Comment by afragen** [comment] 2017-05-26 04:55
It's likely a major refactor. It's not the GitLab code but in Base , Plugins, and Themes.

**Comment by afragen** [comment] 2017-05-26 04:58
BTW you subpackage repo doesn't even contain a plugin, only a composer.json

**Comment by sadortun** [comment] 2017-05-26 04:58
Oh.... Because, Once the plugin has been downloaded, the rest of the structure is identical, the only difference is the git repository URL format.

I did submit a PR to have Packagist support this feature and it was a simple tweak in a regex ( https://github.com/composer/packagist/pull/784/commits/df3af192f4358189c2e2642215dc00724f84dbba)

**Comment by sadortun** [comment] 2017-05-26 05:03
> BTW you subpackage repo doesn't even contain a plugin, only a composer.json
Yes, i know, it was an example to give you the path only.

Do you need a public sample project for testing ?

**Comment by afragen** [comment] 2017-05-26 05:09
No, don't need an actual plugin. The code isn't designed to parse for anything other than https://gitlab.com/owner/repo

Even with Bitbucket Server the URI doesn't work to fit to the repo but parses correctly to create the correct paths.

**Comment by afragen** [comment] 2017-05-26 13:57
If your interested I think this is what would need modification,
https://github.com/afragen/github-updater/blob/develop/src/GitHub_Updater/Base.php#L845-L896

Remember it still needs to work exactly as it currently does.

**Comment by jb510** [comment] 2017-05-29 16:43
Correct me if I'm wrong but Teams and Groups are features of GitLab only, not part of the git spec the way submodules are (or to an extent subtrees are).  I wouldn't expect others to adopt something identical.

It would be cool if GHU supported more complex repos (like those with sub-modules or sub-tress) but I imagine that's a HUGE rebuild/refactor.

**Comment by afragen** [comment] 2017-05-29 16:50
The way the OP had written the example, it looks to be in the format as follows. 

`https://gitlab.com/owner/subfolder/repo`

As long as this is consistent I might be able to find a solution. Also think `subfolder == project`

**Comment by jb510** [comment] 2017-05-29 22:58
@afragen sorry I came into this thread with the mindset of it being related to my question about managing full sites and thinking the OP wanted to update groups.  Disregard.

**Comment by afragen** [comment] 2017-05-30 04:01
@jb510 I interpreted your problem as similar in that the problem isn't some arbitrary name or subgroups or projects but how the repository is organized. 

If I understand correctly it's about having the main plugin or theme folder inside a folder of a root and not simply inside the root. 

Does that sound right?

**Comment by jb510** [comment] 2017-05-30 13:06
If I under understand this issue correctly, no they are very different things.  The OP is stating the GHU fails to correctly parse a GitLab repo url when it includes a team/group/sub-group facet. The group is just an organizational feature on GL that adds a facet to the repo url. The url still only references a single repo folder and a single repo, it just look like GL/group/sub-group/repo_name instead of GL/repo_name.   

GL does not do anything magic to create a functional relationship between repos placed in a group. GL does not for example provide access to /group/* where that represents multiple repos. That'd be cool, but access like that is not available.

**Comment by afragen** [comment] 2017-05-30 13:27
Somewhere I think I'm confused about this. We should be able to clear it up at WCOC.

**Comment by sadortun** [comment] 2017-05-30 15:47
@jb510 exact. This is just a matter or repository URL. Nothing more. There should just be no assumsions on the URL path and expect any URL to be a valid repository URL.

**Comment by afragen** [comment] 2017-05-30 16:14
The issue I just thought about was an accurate download link. I'm not sure that a _repo_ in a subfolder of root will be able to have an appropriate download link.

**Comment by trombini77** [comment] 2017-06-07 23:21
I saw this issue today because I used the Subgroup feature in the GitLab and I tried to use this plugin and really is not already support this GitLab feature.

Well in fact is not a issue but a feature that GitLab made at Mar 2017 as link bellow https://about.gitlab.com/2017/03/22/gitlab-9-0-released/ so is more right to think that is a new feature.

I was looking in the code that filter the URI that is inputed in the Theme URI or Plugin URI and I saw in the API.php the get_api_url() function.

It receives also the provider (Github, GitLab or Bitbucket) parameter so maybe a new algorithm to filter this content when is selected GitLab (between $segments definition and before the switch ($type['repo´]) ) maybe would be a good way. Is only a brainstorm that I had :)

Sorry don´t have now time to test any kind of change in the next 15 days, but in the next month I guess maybe can help with this.

**Comment by afragen** [comment] 2017-06-07 23:28
The issue with support of this is whether or not GitLab can provide a download link for each individual subgroup and is that link syntax consistent?

**Comment by afragen** [comment] 2017-06-07 23:32
If someone had a group set up that they could grant me read access to that would help.

**Comment by jb510** [comment] 2017-06-07 23:40
@afragen I just moved all our repos (100) from separate groups to sub-groups.  I can discuss this weekend at WordCamp Orange County or in Slack (just ping me)

**Comment by sadortun** [comment] 2017-06-07 23:49
> The issue with support of this is whether or not GitLab can provide a download link for each individual subgroup and is that link syntax consistent?

This is the exact same thing,  Project were only in groups, and now can be in groups and sub-groups. Download URL are related to projects, and are still available with the same API as before.

Groups and sub-groups only affects the URL of the repository, the mecanism to access API and download URL remains the same.

**Comment by afragen** [comment] 2017-06-08 04:17
Time to test. Let me know how branch `gitlab-groups` works.

**Comment by afragen** [comment] 2017-06-08 04:23
BTW, the URI to put in the header is in the following format: `https://gitlab.com/<owner>/<group>/<repo>`.

I am not able to support subgroups of groups. I need to have a limit.

**Comment by afragen** [comment] 2017-06-08 16:16
Just pushed https://github.com/afragen/github-updater/commit/9d1a24f285a13443e6174c2905db7485dcb25e94

It should allow any number of subgroups. Use branch switch to refresh `gitlab-groups` 👍

**Comment by afragen** [comment] 2017-06-17 16:37
Has anyone else been able to test the `gitlab-groups` branch?

**Comment by rolandsaven** [comment] 2017-06-24 15:31
@afragen I tested the `gitlab-groups` branch and it is working ok. I've also submitted a new pull request. See if that makes any sense, my thinking could be wrong. see #563

**Comment by afragen** [comment] 2017-06-26 23:47
@rolandsaven thanks for the PR. I used concept of groups as an extended owner and updated the branch accordingly.

**Comment by afragen** [comment] 2017-06-29 03:29
This is now merged into `develop`. Anyone testing this branch just needs to update when they see the notification and the update will put you back on the `develop` branch.

**Closed by afragen** 2017-06-29 03:29 UTC
Labels: feature-request, testing

**Comment by noplanman** [comment] 2020-11-13 16:59
This has become a problem again for me I think. Some time ago GHU has stopped working, but I don't know at what version.

I noticed that the code to parse the headers has changed in the latest version and isn't like your initial commit to introduce the feature.

For the others in this issue, does GHU still work for you with subgroups?

**Comment by afragen** [comment] 2020-11-13 17:26
The support plugin just bypasses the WP-Cron background API updates. This is perhaps a sign that you are having issues with WP-Cron.

**Comment by afragen** [comment] 2020-11-13 17:29
FWIW one of my testing plugins is a private GitLab plugin in a subgroup.

**Comment by noplanman** [comment] 2020-11-13 17:45
Your replies have just come in after I updated my comment.

It might be that the WP-Cron bypass option isn't working properly for me, but was bypassed correctly by the support plugin.

**Comment by afragen** [comment] 2020-11-13 20:06
The wp-cron bypass option should be identical as it also sets the filter.
