### ISSUE TITLE
AWS links expires and after, Ignores release asset

### ISSUE THREAD

**Issue by geminorum** [afragen/github-updater#615] opened 2017-10-23 17:09 UTC
- the download links provided for assets via aws very soon (in a matter of minutes) will expire and I get `Forbidden` on the first try to install a plugin/theme with asset package. this is happening for a while 🙈 

- in the second try, github-updater ignores the asset package info and installs raw code from the repo. this happened after updating to `7.4.x`

**Comment by afragen** [comment] 2017-10-23 17:17
@geminorum AWS now expires their links after 5 minutes. If you refresh the page immediately before trying to update you should get a new link and update should proceed normally.

If you continue to have issues I might need a repo URL to test.

**Comment by geminorum** [comment] 2017-10-23 17:31
- I've been refreshing for a while now 😄 

- it's better ux to put a refresh link on update page or utilizing core's “check again” button.

- the second try problem is new and it's interfering with my “continous development” routin 😃 

- repo for test: [geminorum/geditorial](https://github.com/geminorum/geditorial), [geminorum/gnetwork](https://github.com/geminorum/gnetwork)

**Comment by afragen** [comment] 2017-10-23 17:38
I'm not sure I understand. All that needs to happen for a download link refresh is a reload of the page.

You will need to further explain your "continuous development" routine.

I'm going to test with one of your repos.

**Comment by afragen** [comment] 2017-10-23 17:44
I was able to install and update geditorial without issue. I installed it, decreased the version number so I would see an update. Then updated. The update utilized the release asset.

**Comment by geminorum** [comment] 2017-10-23 17:45
- the page reload will ignore release asset and installs raw code.
- installing the raw code will result in I manually deleting the plugin and manually installing it again.
- this will defeat the purpose of using github-installer for any plugin/theme with release assets.

**Comment by geminorum** [comment] 2017-10-23 17:49
I got this in just 3 different sites that I tried to update the plugin in the last hour.

**Comment by afragen** [comment] 2017-10-23 17:50
![screenshot_01](https://user-images.githubusercontent.com/1296790/31904387-f0622160-b7df-11e7-86f8-79361d0ef832.png)

How are the sites trying to update? Is someone manually updating or is this via some remote management tool?

**Comment by afragen** [comment] 2017-10-23 17:56
![screenshot_02](https://user-images.githubusercontent.com/1296790/31904680-c73aa888-b7e0-11e7-8269-f33b35da683e.png)
![screenshot_03](https://user-images.githubusercontent.com/1296790/31904683-c881ba2e-b7e0-11e7-8745-2801c24da589.png)

Just tested again using both repos.

**Comment by geminorum** [comment] 2017-10-23 18:00
first try (expired aws)
![chrome_2017-10-23_21-25-58](https://user-images.githubusercontent.com/150718/31904881-447f1de4-b839-11e7-8b12-b8d1a7f76978.png)

second try (installing raw)
![chrome_2017-10-23_21-28-49](https://user-images.githubusercontent.com/150718/31904916-5e1a9904-b839-11e7-9591-55fab1e97373.png)

**Comment by geminorum** [comment] 2017-10-23 18:10
> How are the sites trying to update? Is someone manually updating or is this via some remote management tool?

manually

**Comment by afragen** [comment] 2017-10-23 20:41
You might have to step through `GitHub_API::get_github_release_asset_URL()` to find the error.

**Comment by afragen** [comment] 2017-10-25 21:57
Have you been able to reproduce this locally?

**Comment by geminorum** [comment] 2017-10-26 00:01
on another site:
again on first try (ignores release asset)
![chrome_2017-10-26_03-23-54](https://user-images.githubusercontent.com/150718/32028866-90dbe878-b9fd-11e7-828f-79ca7e365444.png)

after refresh again, on first try (ignores release asset)
![chrome_2017-10-26_03-26-12](https://user-images.githubusercontent.com/150718/32028877-ae326690-b9fd-11e7-95d3-338e34ca8e39.png)

Also I have difficulty storing access token on my local install, but I will try to install fresh test WordPress and test locally.

**Comment by geminorum** [comment] 2017-10-26 00:07
also fresh installer ignores assets completely
![chrome_2017-10-26_03-35-39](https://user-images.githubusercontent.com/150718/32029081-ff8535ee-b9fe-11e7-95ce-d1c476dc6657.png)

**Comment by afragen** [comment] 2017-10-26 02:17
Remote Install has no way to see inside of the headers of a repo that isn't already installed. It's not expected to download a release asset.

I've made a couple of changes in the `develop` branch regarding the `Release Asset` header. I don't know if it will help you though as I can't replicate this.

**Comment by geminorum** [comment] 2017-10-26 20:12
fresh install WordPress 4.9 Beta 4 with a clone of github-updater 7.4.2.1
![chrome_2017-10-26_23-24-46](https://user-images.githubusercontent.com/150718/32074698-2436ccce-baa7-11e7-9dc2-c374db452c9a.png)

same issue (ignoring asset)
![chrome_2017-10-26_23-38-42](https://user-images.githubusercontent.com/150718/32074764-507a66b0-baa7-11e7-8a23-faf3a3e60bf8.png)

**Comment by afragen** [comment] 2017-10-26 20:23
How come the first image of the plugins page doesn't show an update available? How did you update?

**Comment by geminorum** [comment] 2017-10-26 20:34
this is just after activation of your plugin. then I have to put github token, then refresh, then wait, then the new update notification appears. the second screen is for after hitting the update.

**Comment by afragen** [comment] 2017-10-26 20:35
I just was able to replicate. Stay tuned.

**Comment by afragen** [comment] 2017-10-26 22:47
Can you test branch `fix-release-asset` for me?

**Comment by geminorum** [comment] 2017-10-26 23:20
testing with `fix-release-asset` branch
> Update package not available.

![chrome_2017-10-27_02-49-23](https://user-images.githubusercontent.com/150718/32081325-8a14db98-bac1-11e7-8368-e14890423e53.png)

**Comment by afragen** [comment] 2017-10-26 23:31
Is that an error from the timeout?

**Comment by geminorum** [comment] 2017-10-26 23:38
timeouts are usually `Forbidden` with expired aws links, like [this](#issuecomment-338744914)

**Comment by afragen** [comment] 2017-10-27 00:31
Wow, now I can't reproduce this.

**Comment by geminorum** [comment] 2017-10-27 01:59
same `Update package not available.` again. also worth mentioning:
> Automatic update is unavailable for this plugin.

![chrome_2017-10-27_05-23-59](https://user-images.githubusercontent.com/150718/32084704-9573e482-bad7-11e7-9447-fd8f04fa500c.png)

the error apparently is a `WP_Upgrader` string.

**Comment by afragen** [comment] 2017-10-27 02:04
Let me add a few error messages and maybe we can see when this is happening.

**Comment by geminorum** [comment] 2017-10-27 02:33
nothing on the screen but on debug.log
```
[26-Oct-2017 04:49:59 UTC] PHP Notice:  Undefined index: base_uri in K:\Localhost\wpn\wp-content\plugins\github-updater\src\GitHub_Updater\Theme.php on line 152
[26-Oct-2017 04:49:59 UTC] PHP Notice:  Undefined index: owner_repo in K:\Localhost\wpn\wp-content\plugins\github-updater\src\GitHub_Updater\Theme.php on line 152
[26-Oct-2017 04:52:53 UTC] PHP Notice:  Undefined variable: caches in K:\Localhost\wpn\wp-content\plugins\github-updater\src\GitHub_Updater\Base.php on line 498
[26-Oct-2017 04:52:53 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, null given in K:\Localhost\wpn\wp-content\plugins\github-updater\src\GitHub_Updater\Base.php on line 500
[26-Oct-2017 05:01:25 UTC] PHP Notice:  Undefined variable: caches in K:\Localhost\wpn\wp-content\plugins\github-updater\src\GitHub_Updater\Base.php on line 498
[26-Oct-2017 05:01:25 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, null given in K:\Localhost\wpn\wp-content\plugins\github-updater\src\GitHub_Updater\Base.php on line 500
[26-Oct-2017 23:07:40 UTC] PHP Notice:  Undefined property: stdClass::$assets in K:\Localhost\wpb\wp-content\plugins\github-updater\src\GitHub_Updater\GitHub_API.php on line 480
[26-Oct-2017 23:07:40 UTC] PHP Notice:  Trying to get property of non-object in K:\Localhost\wpb\wp-content\plugins\github-updater\src\GitHub_Updater\GitHub_API.php on line 480
```

the first two ( base_uri / owner_repo ) is for after github-updater 7.4.x, but the rest is new.

**Comment by afragen** [comment] 2017-10-27 02:41
I have to go operate on someone. I’ll have to get back to this. Stay tuned.

**Comment by geminorum** [comment] 2017-10-27 02:44
:

**Comment by afragen** [comment] 2017-10-27 03:31
A quick look at the above error shows a likely `wp_remote_get()` error just above that line. Can you report what the result of that call is?

**Comment by geminorum** [comment] 2017-10-27 04:07
`$response = $this->api( '/repos/:owner/:repo/releases/latest' );` returns
```
stdClass Object
(
    [url] => https://api.github.com/repos/geminorum/gnetwork/releases/8207803
    [assets_url] => https://api.github.com/repos/geminorum/gnetwork/releases/8207803/assets
    [upload_url] => https://uploads.github.com/repos/geminorum/gnetwork/releases/8207803/assets{?name,label}
    [html_url] => https://github.com/geminorum/gnetwork/releases/tag/3.6.6
    [id] => 8207803
    [tag_name] => 3.6.6
    [target_commitish] => master
    [name] => 3.6.6
    [draft] => 
    [author] => ...
    [prerelease] => 
    [created_at] => 2017-10-21T18:26:10Z
    [published_at] => 2017-10-21T18:49:14Z
    [assets] => Array
        (
            [0] => stdClass Object
                (
                    [url] => https://api.github.com/repos/geminorum/gnetwork/releases/assets/5129387
                    [id] => 5129387
                    [name] => gnetwork-3.6.6.zip
                    [label] => 
                    [uploader] => ...
                    [content_type] => application/zip
                    [state] => uploaded
                    [size] => 883403
                    [download_count] => 151
                    [created_at] => 2017-10-21T18:47:53Z
                    [updated_at] => 2017-10-21T18:48:05Z
                    [browser_download_url] => https://github.com/geminorum/gnetwork/releases/download/3.6.6/gnetwork-3.6.6.zip
                )

        )

    [tarball_url] => https://api.github.com/repos/geminorum/gnetwork/tarball/3.6.6
    [zipball_url] => https://api.github.com/repos/geminorum/gnetwork/zipball/3.6.6
    [body] => ...
)
```
and `$url = $this->add_access_token_endpoint( $this, $response->assets[0]->url );` returns `WP_Error` object:
```
[http_request_failed] => Array
	(
		[0] => cURL error 28: Operation timed out after 5000 milliseconds with 103993 out of 883403 bytes received
	)
```

**Comment by afragen** [comment] 2017-10-27 04:15
That last line cited should just return the URL with the correct access token added as a query arg. The following line is a `wp_remote_get` which appears to be timing out. Which is the problem. 

Try again later, I hope the timeout issue is temporary.

**Comment by afragen** [comment] 2017-10-27 04:18
At least it now seems to be going after the correct download link. 🤔

**Comment by geminorum** [comment] 2017-10-27 08:28
- however, my point is, if `Release Asset` is set to true then the false result of `get_github_release_asset_url()` must stop the plugin from updating.

- other is that `$url = $this->add_access_token_endpoint( $this, $response->assets[0]->url );` refers to an endpoint that result a [json details](https://api.github.com/repos/geminorum/gnetwork/releases/assets/5129387) of that particular asset. seems to me the `browser_download_url` is the correct link.

**Comment by afragen** [comment] 2017-10-27 13:38
It does stop from updating because the error stopped it. That’s not the same thing as not identifying an update if the download link is incorrect or not present. Trying to not show an update is available simply because of a timeout error is false reporting.

**Comment by geminorum** [comment] 2017-10-27 22:47
It does not just notify, it updates. I posted a plenty of screenshots for this. I'd tried to provide a PR but couldn't follow the logic of your plugin.

**Comment by afragen** [comment] 2017-10-27 23:30
It’s not currently updating is it? I’ve made quite a number of changes and don’t think an update from usual GitHub download happens any longer.

**Comment by afragen** [comment] 2017-10-30 19:40
@geminorum I believe that I have fixed many of the issues that we have discussed. These fixes are in the `fix-release-asset` branch. Can you please see if these fixes help you?

To ensure you have the _latest_ version, please use the branch switcher and re-install the `fix-release-asset` branch prior to testing.

**Comment by geminorum** [comment] 2017-10-31 09:09
![github_2017-10-31_12-37-45](https://user-images.githubusercontent.com/150718/32215829-5b2812b2-be38-11e7-9cd8-bacef05f3d69.png)

![chrome_2017-10-31_12-35-51](https://user-images.githubusercontent.com/150718/32215848-65c21e98-be38-11e7-9c18-61c110cd40c8.png)

```
[31-Oct-2017 09:04:41 UTC] PHP Notice:  Undefined property: stdClass::$assets in K:\Localhost\wpb\wp-content\plugins\github-updater\src\GitHub_Updater\GitHub_API.php on line 480
[31-Oct-2017 09:04:41 UTC] PHP Notice:  Trying to get property of non-object in K:\Localhost\wpb\wp-content\plugins\github-updater\src\GitHub_Updater\GitHub_API.php on line 480
```

**Comment by afragen** [comment] 2017-10-31 19:55
It is still having a timeout issue from line 470 of `GitHub_API::get_github_release_asset_url()`

**Comment by afragen** [comment] 2017-11-04 23:25
Just an FYI, I've merged these into `develop` https://github.com/afragen/github-updater/commit/ccd48b51725686477b5529983d32c5292386de82

**Comment by afragen** [comment] 2017-11-25 17:36
Please reopen this issue if this has not been fixed.

**Closed by afragen** 2017-11-25 17:36 UTC
