### ISSUE TITLE
Plugins not reactivating after an update.

### ISSUE THREAD

**Issue by rayman813** [afragen/github-updater#167] opened 2015-02-24 23:43 UTC
I have tried a few different things, but it seems like no matter what I do with the "update plugin" link on the plugins page, it never reactivates properly.

**Comment by afragen** [comment] 2015-02-25 00:39
How were these plugins originally installed? I ask because the usual GitHub download has extra stuff, like the owner and branch attached to the zip file. As such those plugins can install and activate, but an update will properly rename the directory. Because of the renaming the plugin will not be active. Any subsequent updates should keep the plugin active as the directory name will stay the same.

**Comment by afragen** [comment] 2015-05-15 16:40
@rayman813 are you still having issues?

**Comment by jvhost** [comment] 2015-06-07 09:38
Hello, as of 4.5.5, I've had this same issue (at least I've noticed the issue).

**Comment by afragen** [comment] 2015-06-07 15:12
@rayman813 can you check for me and see what the directory name of the theme is that didn't reactivate? Did it rename correctly?

**Comment by jvhost** [comment] 2015-06-08 00:01
Hi Andy,

Attached are some screenshots (before and after the update).

Hope that helps.  If you want admin access, just let me know.

Thanks,

John

**Comment by afragen** [comment] 2015-06-08 02:02
@jvhost I don't see any screenshots. I'd like to try without admin access if possible.

**Comment by jvhost** [comment] 2015-06-08 02:44
Hi Andy,

Let's try this ..

*Before (relevant folders):*



*After:*

**Comment by afragen** [comment] 2015-06-08 03:50
I think I might know what's happening but thought it was all fixed in 4.5.5
Can you either rename directory on the server or just delete it and reinstall with the remote install feature? 

Can you give `afragen` `read` access on Bitbucket to this repo so I can test locally? Thanks.

**Comment by chefduweb** [comment] 2015-06-08 22:58
I can reproduce this bug with Bitbucket private repositories in 4.5.5 (also while on the /develop branche..

If I can find anything, i'll submit a pull-request...

**Comment by afragen** [comment] 2015-06-08 23:02
I can't seem to reproduce, yet, but look into Base\upgrader_source_selection()`

**Comment by chefduweb** [comment] 2015-06-08 23:21
I think I figured out what was causing the problem. I copied the https value from Bitbucket. This, however as a .git at the end, but if that happends the $git_repo->repo variable used in the function upgrader_source_selection doens't match this if-statement anymore:

if ( $chopped_source_base === $git_repo->repo ) {

I changed the repo-name in my template and now everything works honky-dory.

**Comment by afragen** [comment] 2015-06-08 23:26
Did this cause the plugin not to update or update incorrectly.

**Comment by jvhost** [comment] 2015-06-08 23:50
Hi Andy,

Sorry about the delay .. I gave you read access, you should receive the 
email. The user is ucc-wp-themes.  Renaming the directory on the server 
is possible as a temporary solution but this is going to be used by 
people with various levels of experience so I don't want them having to 
do that.

In the mean time, it looks like Chef du Web got it working .. I'm not 
sure I understand the solution though - did you change the Bitbucket 
Theme URI or Bitbucket Branch or both?  My Theme URI is 
https://bitbucket.org/ucc-wp-themes/t3-red - my branch is master. There 
is no .git on either of those values.

Andy, now that you have access, I'll let you try it.  If you need the 
username and password, I'd prefer emailing you that privately instead of 
this reply - just provide me with your email address if you need it.

Thanks,

John

**Comment by chefduweb** [comment] 2015-06-09 00:04
@afragen the plugin updated incorrectly (it didn't change the folder-name, becaude the if-statement didn't make it).

@jvhost What worked for me was adding my user-name to the Bitbucket Theme URI to:
https://{Username}@bitbucket.org/{repo-name}

I think bitbucket needs a username in the url for private repo's...

**Comment by afragen** [comment] 2015-06-09 01:36
@chefduweb the Bitbucket authentication info is passed from he Settings page.

@jvhost I only need `read` access for my user. I'll let you know what testing shows for me.

**Comment by afragen** [comment] 2015-06-09 02:44
Can both of you switch to `develop` branch either using the branch switcher or update to latest develop and let me know if the bug persists?

**Comment by afragen** [comment] 2015-06-10 14:27
Has anyone had a chance to test against the latest commit on develop? 

@jvhost my tests with your theme now work correctly. 

@chefduweb do the updates work correctly now?

**Comment by jvhost** [comment] 2015-06-10 15:37
Hi Andy,

I just tested it now, much better :).

Thanks for your quick help on this!

John

**Comment by afragen** [comment] 2015-06-10 15:59
Thanks John

**Closed** 2015-06-10 15:59 UTC
