### ISSUE TITLE
HTTP ERROR 500 When activate the plugin after install

### ISSUE THREAD

**Issue by Josecarpeniet** [afragen/github-updater#651] opened 2018-02-19 12:09 UTC
Hi, it doesn´t work. Regards

**Comment by afragen** [comment] 2018-02-19 16:21
500 errors are usually issues with your htaccess file. GHU doesn’t effect this file. You should take a look at https://www.google.com/search?q=500+internal+server+error

More information is always helpful.

**Comment by afragen** [comment] 2018-02-19 16:39
Try the following.

Comment out https://github.com/afragen/github-updater/blob/develop/src/Singleton.php#L39 until I can fix and test. This will likely cause several non-fatal PHP errors.

Once I get a fix tested just update.

**Comment by Josecarpeniet** [comment] 2018-02-20 01:53
Thanks for your reply. I see is not the plugin (I'm not good at all with coding) :)

**Comment by afragen** [comment] 2018-02-20 01:53
Update to latest `develop` branch and let me know if this works.

**Comment by afragen** [comment] 2018-02-20 01:55
@Josecarpeniet debugging is an art and there likely is/was a memory issue in my `Singleton` class that I could improve. Thanks for the report.

**Comment by Josecarpeniet** [comment] 2018-02-20 02:10
Still the same problem, friend. The previous release has not this problem (7.4.3)

**Comment by afragen** [comment] 2018-02-20 02:23
Can you deactivate all plugins except for GitHub Updater and let me know if the problem persists?

**Comment by afragen** [comment] 2018-02-20 15:20
Can you set `define( ‘WP_DEBUG’, true );` in wp-config.php

**Comment by adamsoderstrom** [comment] 2018-02-20 22:27
Had this issue too.
but Reddog's answer in issue #650 solved it for me.

**Comment by afragen** [comment] 2018-02-22 23:33
Closing as duplicate of #650

**Closed by afragen** 2018-02-22 23:33 UTC
