### ISSUE TITLE
Is self-hosted Bitbucket Server (aka Stash) supported?

### ISSUE THREAD

**Issue by BjornW** [afragen/github-updater#368] opened 2016-03-02 17:12 UTC
I'm currently testing Github-Updater with our self-hosted Bitbucket Server installation. I've noticed that if I add a full url in Plugin URI found in Settings->Github Updater Settings -> Install Plugin Tab it still connects to https://bitbucket.org even though I've added our installation's url. 

Is this a bug or is a private self-hosted Bitbucket installation not (yet) supported? If not, what needs to be done to support this? I might be able to send in a PR.

ps: My compliments on your code. My first impression is that it looks well-defined and well-written.  and I'm sure I might learn a thing or two from it :)

**Comment by afragen** [comment] 2016-03-02 20:53
Self-hosted Bitbucket is a relatively new thing and I haven't yet looked at supporting it. Once I figure out the proper URI's for the API calls it should be relatively easy.

As with all these self-hosted or enterprise options, I don't run them so I can't really test. I will need help.

Can you provide a link to the info on self-hosted Bitbucket?

**Comment by BjornW** [comment] 2016-03-03 14:25
Hi @afragen I can help out with testing. This is a link to download a trial of the Bitbucket Server https://www.atlassian.com/software/bitbucket/download As far as I understood there should be no difference in the API thus the only thing preventing the plugin from working with a private self-hosted instance is the use of the bitbucket.org constants in the code. Is there a reason why you are not using the full url found during parsing?

**Comment by afragen** [comment] 2016-03-03 14:35
If Bitbucket Server is self hosted the URI will obviously be different. Can you give me an example of the URI?

I use a shortened version so the majority of users may use a shortened owner/repo designation.

**Comment by BjornW** [comment] 2016-03-03 14:38
For instance this: http://bitbucket.example.com/projects/WOR/repos/wordpress

**Comment by afragen** [comment] 2016-03-03 18:46
How I handled enterprise installations for GitHub and GitLab was with an additional header that lists the base URI, in this case `http://bitbucket.example.com`

I looked online and can't find any API documentation specific for Stash. In your example are `projects` and `repos` constant for all projects and what is `WOR`? owner or repo?

Is `wordpress` the repo?

**Comment by BjornW** [comment] 2016-03-07 12:13
Projects => project (nowadays also on bitbucket.org)

**Comment by BjornW** [comment] 2016-03-07 12:50
I've found the developer docs for (selfhosted) Bitbucket Server (aka Stash): https://developer.atlassian.com/bitbucket/server/docs/latest/

**Comment by BjornW** [comment] 2016-03-07 15:56
So far it seems that creating a downloadable archive is not supported using the default out of the box API. However there is an add-on for Bitbucket Server which claims to support downloadable archives of specific branches. So supporting Bitbucket Server includes having a dependency on this add-on (if it works). I'll continue investigating this option, test the add-on and report back.

**Comment by BjornW** [comment] 2016-03-07 16:37
Docs for the REST API when using the stash-archive add-on https://bitbucket.org/atlassian/stash-archive/src

**Comment by BjornW** [comment] 2016-03-07 17:01
After installing the stash-archive addon it allows you to download files using url as described in the docs, e.g. http://bitbucket.example.com/plugins/servlet/archive/projects/WOR/repos/wordpress where WOR = Project Key

**Comment by afragen** [comment] 2016-03-07 17:05
That last bit of info looks great. I'll see about creating a new branch to test against.

**Comment by BjornW** [comment] 2016-03-07 17:07
Great, I've forked this plugin as well so I can check it out and help with the code if needed :)

**Comment by afragen** [comment] 2016-03-08 04:40
Is there any API call to test whether is add-on is present? Do you know if it fails gracefully?

**Comment by BjornW** [comment] 2016-03-10 13:46
I've looked in the docs and couldn't find anything about checking the existence of an addon. I have asked the Atlassian folks as well. See https://answers.atlassian.com/questions/37544470/check-if-addon-exists.

**Comment by BjornW** [comment] 2016-03-10 14:03
Thanks to [Steffen Opel](https://answers.atlassian.com/questions/37544470/answers/37544618): 
apparently Bitbucket Server always contains an addon manager called UPM (universal plugin manager) which has an undocumented (yeah..) REST API which supports this, although it needs sysadmin credentials to perform this operation. 

See https://ecosystem.atlassian.net/wiki/display/UPM/UPM+REST+API?focusedCommentId=150667274#comment-150667274

**Comment by afragen** [comment] 2016-03-10 18:35
@BjornW you have 2 different _download_ URI examples above.

> http://bitbucket.example.com/projects/WOR/repos/wordpress
> http://bitbucket.example.com/plugins/servlet/archive/projects/WOR/repos/wordpress
> WOR = project key
> wordpress = repo

Which is correct?

Is there an _owner_ associated with Bitbucket Stash? If not we would assume `<project key>/<repo>` for `<owner>/<repo>`

**Comment by afragen** [comment] 2016-03-10 18:50
How does one distinguish between branches in the download URI?

**Comment by afragen** [comment] 2016-03-10 18:58
What is the API for getting all the specific pieces of the repository. (main plugin file, branches, tags, readme, changelog, etc.)

**Comment by afragen** [comment] 2016-03-10 19:23
I think I've figured out the branches and tags part from the docs.

If you want to use the branch switcher and switch to `feature/bitbucket-enterprise` let me know what happens.

**Comment by afragen** [comment] 2016-03-10 19:34
Sorry forgot.

Add `Bitbucket Enterprise:` header with the base URI for your Bitbucket Stash server.

In `Bitbucket Plugin URI:` put `<project>/<repo>`

**Comment by BjornW** [comment] 2016-03-10 20:15
Ok, will check it out.

**Comment by BjornW** [comment] 2016-03-10 20:38
Ok, I've added a fake plugin with nothing more than the magic header in a php file on our Bitbucket server, but it does not yet work. I've used the following:

`/*******************************************************************************
Plugin Name: Test Updater
Plugin URI: http://www.burobjorn.nl
Description: Fake plugin to test github-updater
Author: Bjorn Wijers <burobjorn at burobjorn dot nl> 
Version: 1.0
Author URI: http://www.burobjorn.nl
Bitbucket Enterprise: http://bitbucket.example.com/
Bitbucket Plugin URI: WOR/test-updater
Bitbucket Branch: master

*******************************************************************************/   
`
Btw I've had to change the real enterprise url to example.com, but the real url is accessible and used in the file. The version in the repo is 1.3 and the version installed on WordPress is 1.0

**Comment by BjornW** [comment] 2016-03-10 20:46
Ok, I get a 401 error after ticking the private repo box.

**Comment by afragen** [comment] 2016-03-10 21:51
I'll have to add a user/password section for BitBucket Enterprise. 

Does it work for public repos?

**Comment by BjornW** [comment] 2016-03-13 11:14
I've tried this with setting a repo to public, by ticking the box in the Repository Settings -> Public access 
'Allow users without a Bitbucket account to clone and browse this repository.' is now enabled.

The 401 error message is gone, but it does not detect the difference in versions between the installed plugin and the one in the repository. I''ve added a log ability to gain more insights. Will report back when I have more info.

**Comment by BjornW** [comment] 2016-03-13 12:26
Just to make sure I could access the server properly and making sure the issue is within the plugin I've used cURL to test the url we need to download the zip file. Using the command below (NB: username/password/url changed for obvious reasons) works expected. The zipfile is retrieved without any issues. 

`curl --user my_user_name:my_secret_password http://bitbucket.example.com/plugins/servlet/archive/projects/WOR/repos/wordpress -O`

**Comment by BjornW** [comment] 2016-03-13 15:25
As far as I can tell, the problem lies in how the plugin connects to the BitBucket API. It does not use the custom url, but instead uses the default BitBucket url. Since the 'enterprise' url is only used in the construct_download_link() in Bitbucket_API.php all other functionality uses the default BitBucket base url. 

Considering the difference in the [BitBucket Cloud REST API](https://confluence.atlassian.com/bitbucket/use-the-bitbucket-cloud-rest-apis-222724129.html) and [BitBucket Server API's]( https://developer.atlassian.com/bitbucket/server/docs/latest/) I'm thinking that the Bitbucket API might be better off split in two API's: Bitbucket Cloud and Bitbucket Server in order to support both options, otherwise we will get a lot of if 'enterprise' do X constructs in the current code. 

@afragen: what do you think?

**Comment by afragen** [comment] 2016-03-14 14:29
@BjornW is there any way to create a read-only account for my on your Bitbucket Server and point me to a test plugin?

Given the possible differences in the API I don't know how else to test.

**Comment by BjornW** [comment] 2016-03-14 15:02
I'd like to, but it is not possible due to security constrains :( What did you think about my proposal to divide the Bitbucket API code? I can start with working on this and send a PR when I'm a bit further with.

**Comment by afragen** [comment] 2016-03-14 15:09
It's not necessary to further separate the API. Take a look at the GitHub and GitLab classes and the `add_endpoints()` function.

**Comment by BjornW** [comment] 2016-03-15 15:29
@afragen I'm sorry but I disagree. For instance fetching a file is, as far as I know, not possible with the current Bitbucket Server REST API. So instead of using the current Bitbucket Cloud API call I need to construct the url based on the UI. 

For now I'm going to focus on implementing the Bitbucket Server API and see what works best. When I have something to show I'll let you know.

**Comment by afragen** [comment] 2016-03-15 18:41
@BjornW as I have no platform to test I am more than happy to help with a new class for Bitbucket Stash.

**Comment by BjornW** [comment] 2016-03-15 20:30
@afragen Working on it ;)

**Comment by BjornW** [comment] 2016-03-16 13:51
@afragen it seems only the private meta data is needed in _add_meta_repo_object() or am I missing something? 

The API reponse from Bitbucket Server is pretty limited in repo metadata details and so far I can only retrieve the privacy metadata, unless I'm willing to add several different API calls and combine the response which I'd prefer not to use due to the added overhead.

**Comment by afragen** [comment] 2016-03-16 14:02
The privacy meta data is the important data. Other data is just used to compute a rating and is really optional.

As I see that almost all functions need to be edited, I agree I would be better to create a new class similar to Bitbucket and put the changes there. I can work on the integration aspects of that.

**Comment by afragen** [comment] 2016-03-17 01:43
I've created a new branch `feature/bitbucket-enterprise-api` to work from. See https://github.com/BjornW/github-updater/commit/a8ffcc70067748168d80819b26e2a010be2560bd#commitcomment-16739709

**Comment by afragen** [comment] 2016-03-17 01:53
I didn't include https://github.com/BjornW/github-updater/commit/536d79518656214158b412594f8f9c47ae92c857#diff-8156a4fa7373020c866d1bf53137786aR110

**Comment by BjornW** [comment] 2016-03-18 12:28
@afragen The response sent by the Bitbucket Server is an array of lines: each line of text is seperated and put into the array. It is limited to 25 lines by default. Afaik, there is no API call for getting the raw file data unless you're willing to not use the API. The response (from the REST docs): 

`{
    "size": 1,
    "limit": 25,
    "isLastPage": true,
    "start": 0,
    "lines": [
        {
            "text": "print('hello world')"
        }
    ]
}`

**Comment by afragen** [comment] 2016-03-18 13:02
The above response is JSON formatted and `json_decode()` should convert it into an array.

**Comment by BjornW** [comment] 2016-03-18 13:20
Correct and the array will have an item per file line, which file_get_headers() doesn't seem to like. So I wrote this as a wrapper to prepare the data for get_file_headers().

**Comment by BjornW** [comment] 2016-03-18 13:50
@afragen I wonder if it wouldn't be better to retrieve the readme and changelog via a constructed url instead of the API. This would allow us to grab the file at once without any overhead. See also https://answers.atlassian.com/questions/32513893/getting-raw-files-from-bitbucket-server-or-stash-server

**Comment by afragen** [comment] 2016-03-18 15:14
:+1:  for getting the raw files in these instances.

**Comment by BjornW** [comment] 2016-03-24 15:00
@afragen The plugin can check the Bitbucket Server and notices that an update is available, however when I try to perform the update I get a WordPress error: 
<pre>
Downloading update from: 
http://bitbucket.example.com/plugins/servlet/archive/projects/WOR/repos/test-updater?at=release-2
An error occurred while updating Test Updater: Download failed. A valid URL was not provided.
</pre>

Looking at the wp-includes/class-http.php I can see that this error is reserved for empty urls (see around linenr 194/194). Any hints on where to check that the url provided to the update mechanism is not empty?

**Comment by afragen** [comment] 2016-03-24 15:18
If you put that URL into a browser window does it download the project?

**Comment by BjornW** [comment] 2016-03-24 15:23
yes it downloads both via browser as well as via wget (on my VM). I'm thinking the query argument is the culprit?

**Comment by BjornW** [comment] 2016-03-24 15:27
For some reason wp_http_validate_url() doesn't like the url provided.

**Comment by afragen** [comment] 2016-03-24 15:44
I'll take a look but it might be difficult unless I can inject data in there.

**Comment by afragen** [comment] 2016-03-24 15:46
Can you try against the master branch? Maybe it doesn't like dashes in query arg but it looks valid.

**Comment by BjornW** [comment] 2016-03-24 16:31
Ok , I think found it: The Bitbucket Server is on a local network and therefore WordPress does not allow a connection unless `http_request_host_is_external` filter returns true. After this it continues with updating and it states that this was succesfull, however the plugin is completely removed. I'll continue with the bughunt...

**Comment by BjornW** [comment] 2016-03-29 10:24
@afragen: Do you know if the upgrader expects a zip with a subdirectory?

**Comment by afragen** [comment] 2016-03-29 14:34
Not quite sure what you mean but the upgrade is a zipped directory.

**Comment by BjornW** [comment] 2016-03-29 15:50
@afragen: I know, but the devil is in the details:  

The WordPress upgrader/updater needs a plugin update in a zipfile within a subdirectory named after the plugin slug. E.g. 

**Working zipfile** contents: 
<pre>
plugin_slug
  plugin.php 
  another_file.php
  some_directory/
</pre>

**Failed zipfile** contents: 
<pre>
plugin.php 
another_file.php
some_directory/
</pre>

_notice the missing subdirectory_

Without the correct zipfile structure, the WordPress plugin update process looks successful, but it will silently fail and the plugin you wanted to update just disappears. Fixing this requires stash-archive to create a zipfile with the plugin files in a subdirectory named after the plugin slug. The Bitbucket Server add-on stash-archive does not create this out-of-the-box :(

However [Alexandru Guduleasa made a PR with this change in stash-archive](https://bitbucket.org/atlassian/stash-archive/pull-requests/4/add-parameters-prefix-and-path-to-the-rest/diff) which would allow this. Sadly it was not merged due to outstanding requested changes by the authors of stash-archive. I've applied these changes today. Hopefully this will result in stash-archive supporting subdirectories so we can use it together with github-updater for plugin updates. 

A possible other option would be forcing people to structure their Bitbucket Server repositories with an extra subdirectorie, which is annoying and problematic in itself and thus I'd prefer to have stash-archive be extended with a prefix option which github-updater can use in the download link construction.

**Comment by afragen** [comment] 2016-03-29 18:38
@BjornW is seems a you have an excellent grasp of the problem. 

WordPress core requires this format and I'm not sure if there's a way to circumvent it.

**Comment by BjornW** [comment] 2016-03-30 08:04
@afragen I hope so :) 

Anyways I prefer Bitbucket Server to be adapted instead of WordPress, although WordPress should at least notify the user of this instead of failing silently. I've created a [ticket](https://core.trac.wordpress.org/ticket/36373#ticket) to see if this can be fixed. For now I'll focus on getting the changes we need into stash-archive after which we have a first alpha version of the Bitbucket Server API working :grinning:

**Comment by BjornW** [comment] 2016-04-04 14:50
I've forked the [stash-archive addon](https://bitbucket.org/BjornW/stash-archive) (at least for now until the original developers respond on my PR and hopefully merge the prefix option) and added the prefix query argument in github-updater. With my last [commit](https://github.com/BjornW/github-updater/commit/3739cc4c313d7163035ee18021c449dd11e79481) I've verified that Bitbucket Server can be used in combination with github-updater to update plugins. For now I'd describe the quality of the code as alpha, since I've been the only one using and testing it. 

ps: I'm currently working on documenting how one can use Bitbucket Server, my forked stash-archive addon and github-updater to update WordPress plugins.

**Comment by BjornW** [comment] 2016-04-18 11:07
@afragen I've just added theme support for Bitbucket Server(https://github.com/BjornW/github-updater/commit/9d704ecb99ff193466d9a4501f7190167a1da6f5). I'd like to integrate my work on Bitbucket Server, shall I merge with your `feature/bitbucket-enterprise-api` branch (there will be conflicts) and then do a pull-request? Or do you want to cherry-pick my changes?

**Comment by afragen** [comment] 2016-04-18 12:50
Which is going to be easiest? I'd like the commit history to show your work.

**Comment by afragen** [comment] 2016-04-19 02:28
You might try `git rebase` agsinst the branch.

**Comment by afragen** [comment] 2016-04-19 02:31
I still need to work on the private authentication, but I'll get it done. :wink:

**Comment by BjornW** [comment] 2016-04-19 08:28
I'll see what happens when I rebase. Afaik authentication works at the moment, filled in my credentials and it grabs the code.

**Comment by BjornW** [comment] 2016-04-19 08:31
Btw I've created an issue for installing plugins and/or themes via Bitbucket Server, since that's not working yet.

**Comment by afragen** [comment] 2016-04-19 14:40
Thanks for the issue. 

I need to create a separate user/pass area for Bitbucket Server in case someone wants to use both. I did something similar for private GitLab servers.

**Comment by BjornW** [comment] 2016-04-20 14:43
Ah, I see.

**Comment by afragen** [comment] 2016-04-23 01:14
Bitbucket Server user/pass should be available to enter if a plugin or theme using a `Bitbucket Enterprise` header is installed. https://github.com/afragen/github-updater/commit/ba6f6306c5bd20479a09f81db8af4fc6c10f82f8

**Comment by BjornW** [comment] 2016-05-12 16:06
Hi @afragen sorry for the delay. I've just fetched your `feature/bitbucket-enterprise-api` branch and rebased against this. I've encountered plenty of conflicts which I've solved. I've tested the result and it still works as expected. 

A pull-request against your `feature/bitbucket-enterprise-api` is afaik not wise due to the rebase  (otherwise you need to solve the same conflicts?) anyways you can find the result of the rebase in https://github.com/BjornW/github-updater/tree/feature/bitbucket-enterprise-api 

I hope this can be merged with the development branch, if not let me know what needs to be done to make this happen.

**Comment by afragen** [comment] 2016-05-12 18:06
Make a PR against the feature branch. There shouldn't be nearly the number of conflicts from my end as you've fixed them. 

I'm excited to get this merged. You've done great work!

**Comment by afragen** [comment] 2016-05-12 18:09
I can create a test branch to merge against and we can see how that works?

**Comment by BjornW** [comment] 2016-05-12 20:02
@afragen seems like a good idea to me :+1:

**Comment by afragen** [comment] 2016-05-13 00:37
I've created `feature/bitbucket-enterprise-test-merge`. Let's see how it works.

**Comment by BjornW** [comment] 2016-05-13 09:09
Allright if you've pushed to Github let me know and I'll test it with my current Bitbucket Server instance.

**Comment by afragen** [comment] 2016-05-13 14:11
@BjornW there's a new branch available for you you to put in a test PR. 

If you've cleaned up against the rebase just submit a PR and I'll clean up anything that remains.

**Comment by afragen** [comment] 2016-05-15 16:29
Are your changes up on GitHub? Is so, I might be able to test the merge locally.

**Comment by afragen** [comment] 2016-05-16 03:19
I think I've tested correctly and if so it should work fine. Go ahead and make a PR against the `feature/bitbucket-enterprise-api` branch.

**Comment by afragen** [comment] 2016-05-21 21:27
@BjornW I've done a merge on from your branch into `feature/bitbucket-enterprise-api`. Can you test and make sure it still works?

I changed a few variable names, modified a few things, and fixed spacing and such. I didn't keep the Log class as it's not really part of the project.

**Comment by BjornW** [comment] 2016-05-22 12:40
@afragen sorry for the delayed response. I'll have a look now and test it.

**Comment by afragen** [comment] 2016-05-22 15:47
Thanks, I'm looking forward to merging. :+1:

**Comment by BjornW** [comment] 2016-05-23 12:29
I've encountered this issue after a `git pull upstream feature/bitbucket-enterprise-api`: 

> PHP message: PHP Fatal error:  Cannot use object of type stdClass as array in /var/www/wpcontrol.tmp/wp-includes/http.php on line 284

I'm currently investigating what caused this, but it will take me some time due to family & work obligations this week.

**Comment by afragen** [comment] 2016-05-23 12:44
That's strange. The error points to a page not part of GHU. You may want to just DL a copy of that branch and see if that works.  Whatever you think will work best and take your time, family first.

**Comment by afragen** [comment] 2016-05-30 23:56
@BjornW you will need to rebase or pull the upstream version down again. I've merged in the latest `develop` branch here. Hopefully it will make the final merge that much easier.

**Comment by afragen** [comment] 2016-06-14 14:33
@BjornW if you're on trunk this might be the cause of the following error.

https://core.trac.wordpress.org/ticket/33055

> I've encountered this issue after a git pull upstream feature/bitbucket-enterprise-api:

>> PHP message: PHP Fatal error: Cannot use object of type stdClass as array in /var/www/wpcontrol.tmp/wp-includes/http.php on line 284

> I'm currently investigating what caused this, but it will take me some time due to family & work obligations this week.

**Comment by afragen** [comment] 2016-06-26 15:25
Hey @BjornW have your latest issues cleared up? Are we closer to merge?

**Comment by BjornW** [comment] 2016-06-27 20:39
Hi @afragen, sorry was a bit occupied with family & work. Will pick it up asap & report back.

**Comment by afragen** [comment] 2016-07-19 04:11
Hey @BjornW just checking in. How's everything? Any free time on the horizon?

**Comment by BjornW** [comment] 2016-08-03 20:09
Sorry, free time is pretty scarce at the moment. Kids, work and renovating our house pretty much fills up my days at this moment. Hopefully my schedule clears up in the middle of September to finalize the merge. Sorry to be the delaying factor!

**Comment by afragen** [comment] 2016-08-03 21:25
Don't worry. I'll try to keep the branch updated so there are fewer possible conflicts. Of course that means you'll have to rebase a bunch.

**Comment by 11mb** [comment] 2016-11-14 13:32
Thx for taking the time to implement this feature! Is this something that will be merged to master soon? I'm testing this feature branch in my project, but I'm wondering about two things:

- It is unclear to me where I can put the login credentials. I don't see any fields for this.
- I get the error message:
 https://bitbucket.company-name.nlprojects/PROJ/get/master.zip…

notice the missing slash in the url.

**Comment by afragen** [comment] 2016-11-14 14:39
@11mb I don't have a self-hosted Bitbucket Server account that I can test with. I'm doing my best to keep up and bring parity to make it quicker to merge once testing is completed.

If you have a plugin/theme installed that has a `Bitbucket Enterprise: ` header you will see a `Bitbucket Enterprise` tab in Settings where you can enter the credentials. You will need to update to the latest version of that branch.

**Comment by afragen** [comment] 2017-02-02 21:39
At present there's no way to install a repo from an enterprise installation.

**Comment by afragen** [comment] 2017-02-12 01:06
@11mb I believe the issue with the missing slash is now fixed.

You won't see the Bitbucket Server tab where you enter credentials until you actually have a plugin/ theme already installed. Sorry sort of a catch-22.

**Comment by 11mb** [comment] 2017-02-13 10:36
Thx for the update, and hard work :) . Currently I'm not working anymore on the projects where I needed this functionality but I will inform my colleague, who is still working in these projects, about this fix!

**Comment by afragen** [comment] 2017-02-13 14:28
@11mb if your friend can provide an account for me on his Bitbucket Server installation I could make quicker progress with this.

**Comment by lkistenkas** [comment] 2017-02-21 11:03
Hi @afragen 

I'm the co-worker @11mb  was talking about. I'm currently working on our wordpress projects, and I'm trying to get you access to our Bitbucket environment. 

We can create a project and some empty repositories for you, this way you would only need git access. If you can send your public key to me, I can whitelist it in our bitbucket server.

**Comment by afragen** [comment] 2017-02-21 14:28
@lkistenkas thanks so much for the offer. The authentication currently is via Basic Auth and requires a username and password, so I would actually need an account for a period of time. An SSH key won't work. 

You are correct in that all I would need to create is a public and a private empty plugin.

Please read through this issue as I believe the Bitbucket Server installation must include the _stash archive addon_.

**Comment by lkistenkas** [comment] 2017-02-22 07:36
@afragen I've sent a request to our administrator to create an account and install the stash archive plugin. 

Once I have confirmation on those things I'll let you know. This probably will be beginning of next week as I don't work on thursday and friday.

**Comment by lkistenkas** [comment] 2017-02-22 11:09
@afragen I've send you an email with the account details

**Comment by afragen** [comment] 2017-02-22 14:29
@lkistenkas thanks. I appreciate it.

**Comment by afragen** [comment] 2017-02-24 00:36
@lkistenkas I've created an empty plugin but I need you to confirm that the stash-archive plugin is installed.

https://bitbucket.org/BjornW/stash-archive/src

**Comment by afragen** [comment] 2017-02-24 01:00
I'm having some authentication issues when trying to Install and as far as I know it's all correct. Grabbing the URI and putting it in a new browser window does download the file.

**Comment by afragen** [comment] 2017-02-24 04:43
I think I'm figuring this out. Stay tuned.

**Comment by afragen** [comment] 2017-02-24 23:21
@BjornW @11mb @lkistenkas I think I've gotten everything working. Can you test `feature/bitbucket-enterprise-API`?

Should be able to merge to `develop` by end of the weekend.

**Comment by afragen** [comment] 2017-02-25 04:20
BTW, need to have official Atlassian stash-archive plugin installed.

**Comment by lkistenkas** [comment] 2017-02-27 07:19
@afragen Hi Andy, you've been busy while I was away ;-) 

I'll test it within the next 3 days

**Comment by afragen** [comment] 2017-02-27 14:51
@lkistenkas everything's now in the develop branch. If you keep updating the branch `bitbucket-enterprise-api` you're on it should automatically switch to the develop branch and then show another update to be current.

**Comment by lkistenkas** [comment] 2017-03-01 13:59
@afragen Hi Andy,

I've tried to test it, but I don't get it to work yet.

What I've done:
1. I uninstalled the previous github updater plugin.
2. I've downloaded the develop.zip from github  and installed it
3. I've tried to install your test plugin, but it won't download, I've tried several different url's as plugin uri:
3.1 https://bitbucket.nedbase.nl/projects/ANDY/repos/test-bitbucket-server-plugin  which is rewritten to https://bitbucket.nedbase.nl/rest/archive/1.0/projects/projects/repos/ANDY/archive?prefix=ANDY/&at=master  for the download but that url doesn't exist.
3.2 I've tried the zip url from bitbucket: https://bitbucket.nedbase.nl/rest/archive/latest/projects/ANDY/repos/test-bitbucket-server-plugin/archive?format=zip but that was rewritten as well to someting that didn't resolve. 


Maybe I'm trying the incorrect url's to install?


These are the other settings I've tried in the plugin install form:
![image](https://cloud.githubusercontent.com/assets/1849767/23462753/5e89746e-fe8f-11e6-8a69-3df0c2c81759.png)


the next coming days I won't be available, but I can try to test it again beginning of next week.

**Comment by afragen** [comment] 2017-03-01 15:00
I know you're already a project admin, I just added you specifically that repo with read access. Please try again and let me know what the error shows. 

The URI you should use to install is `https://bitbucket.nedbase.nl/ANDY/test-bitbucket-server-plugin`

I know this doesn't match the actual URI to get to the repo but it contains all the necessary information in the same format as all other git servers.

**Comment by BjornW** [comment] 2017-03-01 15:10
Hi @afragen & @11mb,

I can help testing after 14th of April. Let me know. I'll try to keep an eye on this issue.

**Comment by afragen** [comment] 2017-03-01 15:14
@BjornW I'm basing the solution off the official stash-archive plugin as above.

**Comment by BjornW** [comment] 2017-03-01 15:21
Yep, the official stash-archive plugins has added my reworked patch sometime ago and it should work unless they changed it? @afragen I'm thinking it would be nice to have a VM which installs the Atlassian stuff so it's easier for testing Bitbucket Server. What do you think?

**Comment by afragen** [comment] 2017-03-01 15:27
@BjornW I think it would depend a lot on your specific local environment. I'm currently using Local by Flywheel and don't have any idea how to integrate something like that. From my workflow, all I really need is access to the actual install. Not sure how well it would work short circuiting the GET requests

That said, if it helps you go for it.

**Comment by lkistenkas** [comment] 2017-03-06 09:07
@afragen hi Andy,

I've just tested it again with the url you provided but it didn't work.

It tried to download the package from https://bitbucket.nedbase.nl/rest/archive/1.0/projects/ANDY/repos/test-bitbucket-server-plugin/archive?prefix=test-bitbucket-server-plugin/&at=master 

When I'm not logged and I call this url manually then I get this json:
{"errors":[{"context":null,"message":"You are not permitted to access this resource","exceptionName":"com.atlassian.bitbucket.AuthorisationException"}]}

When I'm logged in it starts downloading the zip file.

Could it be that something goes wrong with authenticating with my username and password. I've tested it with working and wrong credentials (to see if there was a difference) but both attempts delivered the exact same result.

**Comment by afragen** [comment] 2017-03-06 14:29
@lkistenkas can you copy/paste the error? I just tested again using the URI above and it works here. It would likely be a credentials issue.

**Comment by afragen** [comment] 2017-03-06 18:12
This is what I get.
![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/23622924/5bff58e8-0255-11e7-9292-9325fb820e84.png)
![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/23622928/60e13390-0255-11e7-844d-4dce85d6533c.png)

**Comment by lkistenkas** [comment] 2017-03-07 08:32
@afragen 

My attempt (with another password ofcourse ;-)):

![image](https://cloud.githubusercontent.com/assets/1849767/23647897/8c3556b6-0318-11e7-9fa8-f297fb560675.png)


delivers this result:

![image](https://cloud.githubusercontent.com/assets/1849767/23647929/b1c43fd2-0318-11e7-97d0-b91a1a4b5e4a.png)


Is it possible to add some debug information about what is going wrong?

**Comment by afragen** [comment] 2017-03-07 20:15
I uploaded a plugin, https://github.com/afragen/http-debug-info

When active it will show you the HTTP API responses. You will need to click on the created link and it will show the results in a thickbox.

It skips any calls to `wordpress.org` and it doesn't work on AJAX calls.

From the Install results it will show you the headers. Specifically look at the Authorization header and you can [base64_decode](https://www.base64decode.org) the results to see if your `user:pass` is correct.

**Comment by lkistenkas** [comment] 2017-03-08 07:21
@afragen very nice, thank you. I hope I can take a look into it today, if not I will beginning of next week.

**Comment by afragen** [comment] 2017-03-08 15:17
@lkistenkas thanks. The debug plugin may cause some PHP error about extra characters on activation, sorry.

Also, just to make sure you are using the latest `develop` branch for testing?

**Comment by lkistenkas** [comment] 2017-03-13 07:59
@afragen Hi Andy,

I've enabled the http debug module and I've updated the github updater on the latest develop branch.

What I understand from the code of the http debug module is that I should see a View HTTP debug content link somewhere, but I'm not getting this link somewhere. At least not after an attempt to install the bitbucket test plugin through the github updater.

**Comment by afragen** [comment] 2017-03-13 16:02
So on a clean install with only GHU `develop` and HTTP Debug Info active, I install the plugin from the Install tab as above.

![screenshot_01](https://cloud.githubusercontent.com/assets/1296790/23862946/9f2b46ba-07cb-11e7-9ba8-a726ae06bec4.png)

Opening the link I see the following.

![screenshot_02](https://cloud.githubusercontent.com/assets/1296790/23862960/a9319e16-07cb-11e7-96db-ca895948ce9b.png)

You can run the Basic Auth header through base64 decrypt to add your "username:password" and ensure it is correct.

**Comment by lkistenkas** [comment] 2017-03-14 09:38
Hi @afragen 

For some reason it won't work with my test installation, I've disabled all plugins except GHU and HTTP Debug, and I get debug links everywhere, except when I try to install a plugin. 

Perhaps because I use Bedrock but I believe this shouldn't matter.

I'm going to take a deeper look into it, but that will be in a few weeks as I'll be busy on projects the next weeks.  I'll let you know when I find something.

**Comment by lkistenkas** [comment] 2017-03-14 09:39
@afragen In the meantime I do want to thank you for your quick responses and your help!

**Comment by afragen** [comment] 2017-03-14 13:27
There must be some difference between your setup and mine. I have it working both locally and on a test server. Test server hosted on Siteground. Some caching but nothing fancy. Have you tried to use it with a localhost installation?

I have no idea about Bedrock, sorry.

**Comment by afragen** [comment] 2017-04-14 23:53
@lkistenkas @BjornW have either of you been able to do any further testing?

**Comment by lkistenkas** [comment] 2017-04-18 08:49
hi Andy,

Unfortunatly not, but I still have it on my list, I hope to look into it in the next 2 weeks.



Van: Andy Fragen [mailto:notifications@github.com]
Verzonden: zaterdag 15 april 2017 01:54
Aan: afragen/github-updater
CC: Laurens Kistenkas | Nedbase; Mention
Onderwerp: Re: [afragen/github-updater] Is self-hosted Bitbucket Server (aka Stash) supported? (#368)


@lkistenkas<https://github.com/lkistenkas> @BjornW<https://github.com/BjornW> have either of you been able to do any further testing?

**Comment by BjornW** [comment] 2017-04-19 19:21
No I haven't yet.

**Comment by afragen** [comment] 2017-04-19 20:32
I may just push this to master and we can open new issues as they arise. I'll let you know here.

**Comment by afragen** [comment] 2017-04-27 03:43
I'm closing this issue. I've merged Bitbucket Server support into master and we can create new issues as they arise. 🤓

Thanks @BjornW and @lkistenkas for all the help getting this figured out. I couldn't have done it without you both.

**Closed by afragen** 2017-04-27 03:43 UTC
Labels: enhancement, feature-request, testing

**Comment by BjornW** [comment] 2017-04-27 17:38
Happy to see our work back in master. Thanks!

**Comment by lkistenkas** [comment] 2017-05-02 11:14
@afragen you're welcome, thank you for doing al the hard work! ;-)

I hope to have some spare time soon to test it again with our setup.
