### ISSUE TITLE
Fatal Error in Readme Parser

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [afragen/github-updater#446] opened 2016-09-15 12:50 UTC
Hello, Andy!

The latest update for the Github Updater causes an internal server error.
PHP fatal error:  Uncaught Error: Call to undefined method Fragen\\GitHub_Updater\\Readme_Parser::parse_readme() in /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Readme_Parser.php:34

**Comment by afragen** [comment] 2016-09-15 13:01
Can you reinstall the plugin? I think you may have an incomplete update.

When I switched to the new README parser I removed that code. I don't see references to it currently. Can you refer me to where this function is called?

**Comment by afragen** [comment] 2016-09-15 13:04
Sorry, this is the method from the parent class \Parser. Please make sure that in the vendor directory class-parser.php exists.

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 13:12
I did a manual update through FTP with the development version and the problem is still there.
No files are missing.

I think I identified the problem. There is a typo in the Readme_Parser.php file: `class Readme_Parser extends \Parser`. It should be `class Readme_Parser extends Parser`.

**Comment by afragen** [comment] 2016-09-15 13:14
That blackslash is present because the Readme_Parser file is namespaced.

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 13:21
I don't know if it helps, but here is a stack trace from my server logs:
```
stderr: #0 /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/GitHub_API.php(190): Fragen\\GitHub_Updater\\Readme_Parser-&gt;__construct('# GitHub Update...')
stderr: #1 /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(392): Fragen\\GitHub_Updater\\GitHub_API-&gt;get_remote_readme()
stderr: #2 /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php(211): Fragen\\GitHub_Updater\\Base-&gt;get_remote_repo_meta(Object(stdClass))
stderr: #3 /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(233): Fragen\\GitHub_Updater\\Plugin-&gt;get_remote_plugin_meta()
stderr: #4 /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(193): Fragen\\GitHub_Updater\\Base-&gt;forced_meta_update_plugins()
stderr: #5 /p in /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Readme_Parser.php on line 34
```

**Comment by afragen** [comment] 2016-09-15 13:35
I'm not seeing this in any of my sites that I just updated and refreshed transients.

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 13:41
This is a really strange issue. I did a test on localhost on it works as expected.
It looks like the server can't find the Parser class. The logs below show that PHP uses `\\` in the class name when it tries to retrieve it. 
I haven't worked with namespaced classes so far but this doesn't seem right.

```
PHP Fatal error:  Class 'Fragen\\GitHub_Updater\\Parser' not found in /home/eusebiu/public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Readme_Parser.php on line 25
PHP Fatal error:  Class 'Fragen\\GitHub_Updater\\Parser' not found in /public_html/wp-content/plugins/github-updater/src/GitHub_Updater/Readme_Parser.php on line 25
```

**Comment by afragen** [comment] 2016-09-15 13:50
That error looks like php is trying to include class Parser in the Fragen\GitHub_Updater namespace. It shouldn't as `class Readme_Parser extends \Parser` should escape the namespace.

**Comment by afragen** [comment] 2016-09-15 13:51
I have to go for a couple of hours but I'll be back.

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 13:53
Sure, no problem.

**Comment by curtisbelt** [comment] 2016-09-15 14:43
@EusebiuOprinoiu I haven't seen this error (but I had another one which I reported separately). But I can see if I can reproduce your error on my server, does the error occur on certain pages of Wordpress or on any page load?

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 14:45
The error is present on all admin pages. The front-end is not affected.

**Comment by curtisbelt** [comment] 2016-09-15 15:09
@EusebiuOprinoiu Sorry I am not experiencing that error. What PHP version is your server and your localhost? My server is on on PHP 5.3.10

**Comment by afragen** [comment] 2016-09-15 15:11
I have a fix in mind. I'll try to test today. 

My assumption is that `class Parser` is used and loaded elsewhere in your setup. I'll try namespacing it.

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 15:15
@curtisbelt  I'm on a server running Ubuntu 16.04 with PHP 7.0.8.
@afragen Thank you for trying to solve this. Let me know when you have a package I can test.

**Comment by afragen** [comment] 2016-09-15 16:28
Can you install the latest develop branch. I've pushed a commit to hopefully fix this.

Let me know if it works and I'll push out a hotfix.

**Comment by EusebiuOprinoiu** [comment] 2016-09-15 16:51
The issue is gone! :)
Thank you very much for solving this so quickly!

**Comment by afragen** [comment] 2016-09-15 16:53
Great, I'll close this out and release a hotfix.

**Closed by afragen** 2016-09-15 16:53 UTC
