### ISSUE TITLE
Breaks when GitHub Access Token is Removed

### ISSUE THREAD

**Issue by jay-oswald** [afragen/github-updater#706] opened 2018-08-02 02:18 UTC
I added a private plugin using an Access Token, and everything was working properly.

Then I removed my Access Token and GitHub Updater got stuck on WP-Cron not updating, like in #703 

It would not do anything, was just stuck, and there was no GitHub sub-tab under the settings, to update the key.

I went into the database and manually updated the GitHub Access Token in the github_updater option

It started working properly again.

The WP-Cron needs to detect if the API key does not have access to repos and throw some kind of error if it gets stuck.
Or  if it detects any GitHub headers in any plugin at least unlock the GitHub Settings tab so that you can update the Access Token

**Comment by afragen** [comment] 2018-08-02 02:54
There should have been a GitHub subtab as GitHub Updater, at a minimum, would’ve caused it to be created. The only reason it wouldn’t have been created is if WP-Cron wasn’t running.

The Access Token isn’t required, except for a private repo. Even then, the GitHub subtab should show and a place for the access token next to the repo should be shown.

I encourage you to see if you can replicate this. If you can, install the https://github.com/afragen/github-updater-support plugin. Activating the support plugin will install a number of other plugins and set GitHub Updater to not use WP-Cron for updating. The other plugins installed should assist in figuring out what the issue is.

**Comment by jay-oswald** [comment] 2018-08-02 03:05
It seams to only add the GitHub Tab if there is a not properly formatted key, or one that has never worked, if it is a properly formatted GitHub Key and it has work it does not seam to add the tab.

With the support plugin installed, when I do the same thing, delete my access token, and refresh cache, instead of getting stuck in WP-Cron it returns an error

```
GitHub Updater Error Code: 401	
There is probably an access token or password error on the GitHub Updater Settings page.
```

**Comment by afragen** [comment] 2018-08-02 03:25
That’s the admin notice that shows when a repo needs an access token or Bitbucket user/pass is incorrect.

The GitHub tab is added if there are plugins with the `GitHub Plugin URI`. Since this exists in the GHU plugin it should always show.

Can you screenshot the GitHub subtab?

**Comment by afragen** [comment] 2018-08-02 03:26
Also, are there any HTTP GET errors in Query Monitor? Or anything in the debug.log?

**Comment by afragen** [comment] 2018-08-02 03:30
If GHU doesn’t complete **all** API calls when using WP-Cron, WP-Cron will never finish as GHU will continually re-try to complete those calls. This is why it appears stuck on WP-Cron.

**Comment by jay-oswald** [comment] 2018-08-03 01:12
With the debug plugin enabled then it seams to fail, and the github sub tab re-appears, however with it disabled and stuck in the WP-Cron loop then it seams to never "fail" and the github tab stays hidden

**Comment by afragen** [comment] 2018-08-03 01:15
What is failing? What are the error messages or HTTP API Call errors?

**Comment by afragen** [comment] 2018-08-21 05:06
Any updates @jay-oswald ?

**Comment by afragen** [comment] 2018-09-12 15:17
Going to close this as I couldn’t replicate and I haven’t heard anything further. Please re-open if this persists. Thanks.

**Closed by afragen** 2018-09-12 15:17 UTC
